-- Generated by packages/debate-tournaments/scripts/sync-upstream.mjs from
-- https://github.com/debate/debate-tournament-tabroom.git @ 75239a31cd8523d31dc119fe994b3fec488e77f3
-- (indexcards/tests/test.sql). Do not edit — change the converter or upstream instead.
-- Skipped tables: session.

CREATE TABLE IF NOT EXISTS "ad" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "filename" TEXT DEFAULT NULL,
  "url" TEXT DEFAULT NULL,
  "sort_order" INTEGER DEFAULT NULL,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "approved" INTEGER NOT NULL DEFAULT 0,
  "background" TEXT DEFAULT NULL,
  "person" INTEGER NOT NULL,
  "approved_by" INTEGER NOT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ad__person" ON "ad" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ad__approved_by" ON "ad" ("approved_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "autoqueue" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "active_at" TEXT DEFAULT NULL,
  "message" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "created_by" INTEGER NOT NULL DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ballot" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "side" INTEGER NOT NULL DEFAULT 0,
  "speakerorder" INTEGER NOT NULL DEFAULT 0,
  "seat" TEXT DEFAULT NULL,
  "chair" INTEGER NOT NULL DEFAULT 0,
  "bye" INTEGER NOT NULL DEFAULT 0,
  "forfeit" INTEGER NOT NULL DEFAULT 0,
  "tv" INTEGER NOT NULL DEFAULT 0,
  "audit" INTEGER NOT NULL DEFAULT 0,
  "approved" INTEGER DEFAULT NULL,
  "judge_started" TEXT DEFAULT NULL,
  "started_by" INTEGER DEFAULT NULL,
  "entered_by" INTEGER DEFAULT NULL,
  "audited_by" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "panel" INTEGER NOT NULL DEFAULT 0,
  "entry" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ballot__ballot_ejp" ON "ballot" ("entry", "judge", "panel");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ballot__ballot_sideorder" ON "ballot" ("panel", "judge", "side", "speakerorder");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ballot__uk_ballots" ON "ballot" ("judge", "entry", "panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__panel" ON "ballot" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__judge" ON "ballot" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__audited_by" ON "ballot" ("audited_by");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__entered_by" ON "ballot" ("entered_by");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__entry" ON "ballot" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ballot__started_by" ON "ballot" ("started_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "campus_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL DEFAULT '',
  "uuid" TEXT DEFAULT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "marker" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "tourn" INTEGER NOT NULL DEFAULT 0,
  "panel" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "student" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__panel" ON "campus_log" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__tourn" ON "campus_log" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__school" ON "campus_log" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__entry" ON "campus_log" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__judge" ON "campus_log" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campus_log__person" ON "campus_log" ("person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "caselist" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL,
  "eventcode" INTEGER NOT NULL DEFAULT 0,
  "person" INTEGER NOT NULL,
  "partner" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "caselist__slug" ON "caselist" ("slug");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "caselist__fk_clist_person" ON "caselist" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "caselist__fk_clist_partner" ON "caselist" ("partner");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "category" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "abbr" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "pattern" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "category__category_abbr" ON "category" ("abbr", "tourn");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "category__category_name" ON "category" ("name", "tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category__tourn" ON "category" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "category_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "category" INTEGER DEFAULT NULL,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "category_setting__uk_judge_group_setting" ON "category_setting" ("category", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_setting__category" ON "category_setting" ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "category_setting__category_tag" ON "category_setting" ("category", "tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "change_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "count" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "fine" INTEGER DEFAULT NULL,
  "panel" INTEGER DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "new_panel" INTEGER DEFAULT NULL,
  "old_panel" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__event" ON "change_log" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__tournament" ON "change_log" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__tourn" ON "change_log" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__new_panel" ON "change_log" ("new_panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__old_panel" ON "change_log" ("old_panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__entry" ON "change_log" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__types" ON "change_log" ("tag", "tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__type" ON "change_log" ("tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__created" ON "change_log" ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__person" ON "change_log" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__panel" ON "change_log" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__round" ON "change_log" ("round");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__idx_panel" ON "change_log" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__school" ON "change_log" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "change_log__judge" ON "change_log" ("judge");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chapter" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL DEFAULT '',
  "formal" TEXT DEFAULT NULL,
  "street" TEXT DEFAULT NULL,
  "city" TEXT DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "zip" INTEGER DEFAULT NULL,
  "postal" TEXT DEFAULT NULL,
  "country" TEXT DEFAULT NULL,
  "coaches" TEXT DEFAULT NULL,
  "self_prefs" INTEGER NOT NULL DEFAULT 0,
  "level" TEXT DEFAULT NULL,
  "nsda" INTEGER DEFAULT NULL,
  "district" INTEGER DEFAULT NULL,
  "naudl" INTEGER NOT NULL DEFAULT 0,
  "ipeds" TEXT DEFAULT NULL,
  "nces" TEXT DEFAULT NULL,
  "ceeb" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter__nsda_index" ON "chapter" ("nsda");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter__nsda" ON "chapter" ("nsda");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chapter_circuit" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT DEFAULT NULL,
  "full_member" INTEGER NOT NULL DEFAULT 0,
  "circuit" INTEGER DEFAULT NULL,
  "chapter" INTEGER NOT NULL DEFAULT 0,
  "region" INTEGER DEFAULT NULL,
  "circuit_membership" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "chapter_circuit__uk_chapter_circuit" ON "chapter_circuit" ("chapter", "circuit");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter_circuit__chapter" ON "chapter_circuit" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter_circuit__circuit" ON "chapter_circuit" ("circuit");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chapter_judge" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "first" TEXT DEFAULT NULL,
  "middle" TEXT DEFAULT NULL,
  "last" TEXT DEFAULT NULL,
  "ada" INTEGER NOT NULL DEFAULT 0,
  "retired" INTEGER NOT NULL DEFAULT 0,
  "phone" TEXT DEFAULT NULL,
  "email" TEXT DEFAULT NULL,
  "diet" TEXT DEFAULT NULL,
  "notes" TEXT DEFAULT NULL,
  "notes_timestamp" TEXT DEFAULT NULL,
  "gender" TEXT DEFAULT NULL,
  "nsda" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "person_request" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter_judge__chapter" ON "chapter_judge" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter_judge__person" ON "chapter_judge" ("person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chapter_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "chapter" INTEGER DEFAULT NULL,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "chapter_setting__cs_tag" ON "chapter_setting" ("chapter", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chapter_setting__chapter" ON "chapter_setting" ("chapter");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "circuit" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "abbr" TEXT DEFAULT NULL,
  "tz" TEXT DEFAULT NULL,
  "active" INTEGER DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "country" TEXT DEFAULT NULL,
  "webname" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "circuit_membership" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "approval" INTEGER DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "circuit_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "circuit" INTEGER NOT NULL DEFAULT 0,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "circuit_setting__uk_circuit_setting" ON "circuit_setting" ("circuit", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "circuit_setting__circuit" ON "circuit_setting" ("circuit");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "coach" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "person" INTEGER NOT NULL,
  "entry" INTEGER NOT NULL DEFAULT 0,
  "student" INTEGER NOT NULL DEFAULT 0,
  "nsda" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT DEFAULT NULL,
  "created_by" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "coach__uq_entry" ON "coach" ("entry");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "coach__uq_student" ON "coach" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "coach__entry" ON "coach" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "coach__student" ON "coach" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "coach__person" ON "coach" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "coach__fk_coach_creator" ON "coach" ("created_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "concession" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "price" NUMERIC DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "deadline" TEXT DEFAULT NULL,
  "cap" INTEGER DEFAULT NULL,
  "school_cap" INTEGER DEFAULT NULL,
  "billing_code" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession__fk_concession_tourn" ON "concession" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "concession_option" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "disabled" INTEGER DEFAULT NULL,
  "concession_type" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_option__concession_type" ON "concession_option" ("concession_type");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "concession_purchase" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "quantity" INTEGER NOT NULL,
  "placed" TEXT DEFAULT NULL,
  "fulfilled" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "concession" INTEGER DEFAULT NULL,
  "invoice" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_purchase__school" ON "concession_purchase" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_purchase__fk_cp_concession" ON "concession_purchase" ("concession");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "concession_purchase_option" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "concession_purchase" INTEGER NOT NULL,
  "concession_option" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "concession_purchase_option__uk_purchase_option" ON "concession_purchase_option" ("concession_purchase", "concession_option");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_purchase_option__concession_purchase" ON "concession_purchase_option" ("concession_purchase");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_purchase_option__concession_option" ON "concession_purchase_option" ("concession_option");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "concession_type" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT DEFAULT NULL,
  "concession" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "concession_type__concession" ON "concession_type" ("concession");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "conflict" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "conflicted" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "added_by" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "conflict__uk_constraint" ON "conflict" ("person", "conflicted", "chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conflict__chapter" ON "conflict" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conflict__conflict" ON "conflict" ("conflicted");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conflict__added_by" ON "conflict" ("added_by");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conflict__person" ON "conflict" ("person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "contact" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "school" INTEGER NOT NULL,
  "person" INTEGER NOT NULL,
  "official" INTEGER DEFAULT NULL,
  "onsite" INTEGER DEFAULT NULL,
  "email" INTEGER DEFAULT NULL,
  "book" INTEGER DEFAULT NULL,
  "nsda" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "timestamp" TEXT DEFAULT NULL,
  "created_by" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contact__school" ON "contact" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contact__person" ON "contact" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contact__fk_contact_creator" ON "contact" ("created_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "diocese" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "code" TEXT DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "quota" INTEGER DEFAULT NULL,
  "active" INTEGER NOT NULL DEFAULT 0,
  "archdiocese" INTEGER NOT NULL DEFAULT 0,
  "cooke_award_points" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "diocese__codes" ON "diocese" ("active", "code");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "district" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "code" TEXT DEFAULT NULL,
  "location" TEXT DEFAULT NULL,
  "chair" INTEGER DEFAULT NULL,
  "level" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "realm" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "financials" TEXT DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "district__code" ON "district" ("code");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "email" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "subject" TEXT DEFAULT NULL,
  "content" TEXT DEFAULT NULL,
  "metadata" TEXT DEFAULT NULL,
  "sent_to" TEXT DEFAULT NULL,
  "sent_at" TEXT DEFAULT NULL,
  "sender" INTEGER DEFAULT NULL,
  "sender_raw" TEXT DEFAULT NULL,
  "hidden" INTEGER NOT NULL DEFAULT 0,
  "person" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "email__fk_tourn" ON "email" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "email__sent_at" ON "email" ("sent_at");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "entry" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT DEFAULT NULL,
  "name" TEXT DEFAULT NULL,
  "ada" INTEGER DEFAULT NULL,
  "active" INTEGER NOT NULL DEFAULT 0,
  "dropped" INTEGER NOT NULL DEFAULT 0,
  "waitlist" INTEGER NOT NULL DEFAULT 0,
  "unconfirmed" INTEGER NOT NULL DEFAULT 0,
  "tourn" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "registered_by" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__tournament" ON "entry" ("tourn", "school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__tournament_2" ON "entry" ("tourn", "school", "event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__code" ON "entry" ("code");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__school" ON "entry" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__id" ON "entry" ("id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__event" ON "entry" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry__registered_by" ON "entry" ("registered_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "entry_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "entry_setting__entry_tag" ON "entry_setting" ("entry", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry_setting__entry" ON "entry_setting" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry_setting__tag" ON "entry_setting" ("tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "entry_student" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "entry" INTEGER DEFAULT NULL,
  "student" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "entry_student__uk_entry_student" ON "entry_student" ("entry", "student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry_student__entry" ON "entry_student" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entry_student__student" ON "entry_student" ("student");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "abbr" TEXT DEFAULT NULL,
  "type" TEXT NOT NULL DEFAULT 'attendee',
  "level" TEXT NOT NULL DEFAULT 'open',
  "fee" NUMERIC DEFAULT NULL,
  "code_style" TEXT NOT NULL DEFAULT 'numbers',
  "tourn" INTEGER DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "pattern" INTEGER DEFAULT NULL,
  "rating_subset" INTEGER DEFAULT NULL,
  "nsda_category" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event__event_name" ON "event" ("name", "tourn");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event__event_abbr" ON "event" ("abbr", "tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event__tourn" ON "event" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event__category" ON "event" ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event__nsda_category" ON "event" ("nsda_category");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "event" INTEGER NOT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event_setting__event_tag" ON "event_setting" ("event", "tag");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event_setting__uk_event_tag" ON "event_setting" ("event", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_setting__event" ON "event_setting" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_setting__tag_value" ON "event_setting" ("tag", "value");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_setting__tag" ON "event_setting" ("tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_setting__estag" ON "event_setting" ("tag", "event");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "file" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "type" TEXT DEFAULT NULL,
  "label" TEXT DEFAULT NULL,
  "filename" TEXT DEFAULT NULL,
  "published" INTEGER NOT NULL DEFAULT 0,
  "coach" INTEGER DEFAULT NULL,
  "page_order" INTEGER DEFAULT NULL,
  "uploaded" TEXT DEFAULT NULL,
  "bill_category" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "district" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "webpage" INTEGER DEFAULT NULL,
  "parent" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "file__entry" ON "file" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "file__school" ON "file" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "file__district" ON "file" ("district");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "file__fk_file_tourn" ON "file" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "file__event" ON "file" ("event");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fine" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reason" TEXT DEFAULT NULL,
  "amount" NUMERIC DEFAULT NULL,
  "payment" INTEGER NOT NULL DEFAULT 0,
  "levied_at" TEXT DEFAULT NULL,
  "levied_by" INTEGER DEFAULT NULL,
  "deleted" INTEGER NOT NULL DEFAULT 0,
  "deleted_at" TEXT DEFAULT NULL,
  "deleted_by" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "parent" INTEGER DEFAULT NULL,
  "invoice" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fine__school" ON "fine" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fine__tourn" ON "fine" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fine__levied_by" ON "fine" ("levied_by");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fine__judge" ON "fine" ("judge");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "follower" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "person" INTEGER NOT NULL DEFAULT 0,
  "follower" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "student" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follower__entry" ON "follower" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follower__judge" ON "follower" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follower__school" ON "follower" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follower__follower" ON "follower" ("follower");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follower__type" ON "follower" ("type");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hotel" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "multiple" REAL DEFAULT NULL,
  "surcharge" REAL DEFAULT NULL,
  "no_confirm" INTEGER DEFAULT NULL,
  "tourn_default" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "housing" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "night" TEXT DEFAULT NULL,
  "waitlist" INTEGER NOT NULL DEFAULT 0,
  "tba" INTEGER NOT NULL DEFAULT 0,
  "requested" TEXT DEFAULT NULL,
  "requestor" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "student" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "housing_slots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "night" TEXT DEFAULT NULL,
  "slots" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoice" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "blusynergy" INTEGER DEFAULT NULL,
  "blu_number" TEXT DEFAULT NULL,
  "total" NUMERIC NOT NULL DEFAULT 0.00,
  "paid" INTEGER DEFAULT NULL,
  "school" INTEGER NOT NULL,
  "details" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoice__school" ON "invoice" ("school");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jpool" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "site" INTEGER NOT NULL DEFAULT 0,
  "parent" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool__category" ON "jpool" ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool__parent" ON "jpool" ("parent");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jpool_judge" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "judge" INTEGER NOT NULL DEFAULT 0,
  "jpool" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_judge__pool" ON "jpool_judge" ("jpool");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_judge__judge" ON "jpool_judge" ("judge");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jpool_round" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "jpool" INTEGER DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_round__round" ON "jpool_round" ("round");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_round__jpool" ON "jpool_round" ("jpool");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jpool_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "jpool" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "jpool_setting__uk_jpool" ON "jpool_setting" ("jpool", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_setting__jpool" ON "jpool_setting" ("jpool");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "jpool_setting__jpool_tag" ON "jpool_setting" ("jpool", "tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "judge" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT DEFAULT NULL,
  "first" TEXT DEFAULT NULL,
  "middle" TEXT DEFAULT NULL,
  "last" TEXT DEFAULT NULL,
  "active" INTEGER NOT NULL DEFAULT 0,
  "ada" INTEGER NOT NULL DEFAULT 0,
  "obligation" INTEGER DEFAULT NULL,
  "hired" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "alt_category" INTEGER DEFAULT NULL,
  "covers" INTEGER DEFAULT NULL,
  "chapter_judge" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "person_request" INTEGER DEFAULT NULL,
  "registered_by" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "score" INTEGER DEFAULT NULL,
  "tmp" TEXT DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__id" ON "judge" ("id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__school" ON "judge" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__chapter_judge" ON "judge" ("chapter_judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__person" ON "judge" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__category" ON "judge" ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__alt" ON "judge" ("alt_category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge__fk_judge_registered_by" ON "judge" ("registered_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "judge_hire" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "entries_requested" INTEGER DEFAULT NULL,
  "entries_accepted" INTEGER DEFAULT NULL,
  "rounds_requested" INTEGER DEFAULT NULL,
  "rounds_accepted" INTEGER DEFAULT NULL,
  "requested_at" TEXT DEFAULT NULL,
  "requestor" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge_hire__judge" ON "judge_hire" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge_hire__school" ON "judge_hire" ("school");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "judge_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "conditional" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "judge_setting__uk_judge_setting" ON "judge_setting" ("judge", "tag", "conditional");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge_setting__judge" ON "judge_setting" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "judge_setting__tag" ON "judge_setting" ("tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "message" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "subject" TEXT DEFAULT NULL,
  "body" TEXT DEFAULT NULL,
  "url" TEXT DEFAULT NULL,
  "sender_string" TEXT DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "sender" INTEGER DEFAULT NULL,
  "email" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "visible_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "read_at" TEXT DEFAULT NULL,
  "deleted_at" TEXT DEFAULT NULL,
  "timestamp" TEXT DEFAULT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message__person" ON "message" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message__sender" ON "message" ("sender");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message__fk_message_tourn" ON "message" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message__fk_message_email" ON "message" ("email");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nsda_category" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "type" TEXT DEFAULT NULL,
  "code" INTEGER DEFAULT NULL,
  "national" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "panel" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "letter" TEXT DEFAULT NULL,
  "flight" TEXT DEFAULT NULL,
  "bye" INTEGER NOT NULL DEFAULT 0,
  "started" TEXT DEFAULT NULL,
  "bracket" INTEGER DEFAULT NULL,
  "publish" INTEGER DEFAULT NULL,
  "room" INTEGER DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "panel__room" ON "panel" ("room");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "panel__round" ON "panel" ("round");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "panel_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "panel" INTEGER NOT NULL DEFAULT 0,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "panel_setting__panel_tag" ON "panel_setting" ("panel", "tag");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "panel_setting__uk_panel_tag" ON "panel_setting" ("panel", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "panel_setting__panel" ON "panel_setting" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "panel_setting__setting" ON "panel_setting" ("setting");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "panel_setting__tag" ON "panel_setting" ("tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pattern" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "type" INTEGER DEFAULT NULL,
  "max" INTEGER DEFAULT NULL,
  "exclude" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pattern__tourn" ON "pattern" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "permission" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "district" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "created_by" INTEGER DEFAULT NULL,
  "details" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__chapter" ON "permission" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__region" ON "permission" ("region");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__tourn" ON "permission" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__circuit" ON "permission" ("circuit");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__person" ON "permission" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__category" ON "permission" ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__district" ON "permission" ("district");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "permission__event" ON "permission" ("event");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "person" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT NOT NULL DEFAULT '',
  "first" TEXT DEFAULT NULL,
  "middle" TEXT DEFAULT NULL,
  "last" TEXT DEFAULT NULL,
  "gender" TEXT DEFAULT NULL,
  "pronoun" TEXT DEFAULT NULL,
  "no_email" INTEGER NOT NULL DEFAULT 0,
  "street" TEXT DEFAULT NULL,
  "city" TEXT DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "zip" TEXT DEFAULT NULL,
  "postal" TEXT DEFAULT NULL,
  "country" TEXT DEFAULT NULL,
  "tz" TEXT DEFAULT NULL,
  "phone" INTEGER DEFAULT NULL,
  "provider" TEXT DEFAULT NULL,
  "site_admin" INTEGER DEFAULT NULL,
  "nsda" INTEGER DEFAULT NULL,
  "password" TEXT DEFAULT NULL,
  "accesses" INTEGER DEFAULT NULL,
  "last_access" TEXT DEFAULT NULL,
  "pass_timestamp" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "person__person_email" ON "person" ("email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person__email" ON "person" ("email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person__noemail" ON "person" ("no_email");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person__nsda" ON "person" ("nsda");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "person_quiz" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "hidden" INTEGER NOT NULL DEFAULT 0,
  "pending" INTEGER NOT NULL DEFAULT 0,
  "approved_by" INTEGER DEFAULT NULL,
  "completed" INTEGER NOT NULL DEFAULT 0,
  "answers" TEXT DEFAULT NULL,
  "updated_at" TEXT DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "person" INTEGER NOT NULL,
  "quiz" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_quiz__fk_pq_person" ON "person_quiz" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_quiz__fk_pq_quiz" ON "person_quiz" ("quiz");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "person_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "person_setting__uk_account_setting" ON "person_setting" ("person", "tag");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "person_setting__person_tag" ON "person_setting" ("person", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_setting__person" ON "person_setting" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "person_setting__tag" ON "person_setting" ("tag", "person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "practice" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "chapter" INTEGER NOT NULL,
  "name" TEXT DEFAULT NULL,
  "tag" TEXT DEFAULT NULL,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "reported" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "created_by" INTEGER NOT NULL DEFAULT 0
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "practice__chapter" ON "practice" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "practice__created_by" ON "practice" ("created_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "practice_student" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "practice" INTEGER NOT NULL,
  "student" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "created_by" INTEGER NOT NULL DEFAULT 0
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "practice_student__practice" ON "practice_student" ("practice");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "practice_student__student" ON "practice_student" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "practice_student__created_by" ON "practice_student" ("created_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "protocol" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "protocol__tiebreak_tourn" ON "protocol" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "protocol_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "protocol" INTEGER DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "protocol_setting__tiebreak_set_tag" ON "protocol_setting" ("protocol", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "protocol_setting__tiebreak_set" ON "protocol_setting" ("protocol");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "qualifier" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "result" TEXT DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "qualifier_tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "qualifier__entry" ON "qualifier" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "qualifier__tourn" ON "qualifier" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quiz" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "label" TEXT DEFAULT NULL,
  "questions" TEXT DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "sitewide" INTEGER NOT NULL DEFAULT 0,
  "hidden" INTEGER NOT NULL DEFAULT 0,
  "approval" INTEGER NOT NULL DEFAULT 0,
  "show_answers" INTEGER NOT NULL DEFAULT 0,
  "admin_only" INTEGER NOT NULL DEFAULT 0,
  "badge" TEXT DEFAULT NULL,
  "badge_link" TEXT DEFAULT NULL,
  "badge_description" TEXT DEFAULT NULL,
  "person" INTEGER NOT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "nsda_course" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quiz__person" ON "quiz" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quiz__fk_quiz_tourn" ON "quiz" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quiz__fk_quiz_circuit" ON "quiz" ("circuit");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rating" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "entered" TEXT DEFAULT NULL,
  "ordinal" INTEGER NOT NULL DEFAULT 0,
  "percentile" NUMERIC DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "rating_tier" INTEGER NOT NULL DEFAULT 0,
  "judge" INTEGER DEFAULT NULL,
  "rating_subset" INTEGER DEFAULT NULL,
  "side" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "rating__judge_entry" ON "rating" ("entry", "judge", "side");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rating__entry" ON "rating" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rating__judge" ON "rating" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rating__rating_tier" ON "rating" ("rating_tier");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rating_subset" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rating_tier" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "name" TEXT DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "strike" INTEGER NOT NULL DEFAULT 0,
  "conflict" INTEGER NOT NULL DEFAULT 0,
  "min" NUMERIC DEFAULT NULL,
  "max" NUMERIC DEFAULT NULL,
  "start" INTEGER NOT NULL DEFAULT 0,
  "category" INTEGER DEFAULT NULL,
  "rating_subset" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rating_tier__fk_rating_tier_category" ON "rating_tier" ("category");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "region" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "code" TEXT DEFAULT NULL,
  "quota" INTEGER DEFAULT NULL,
  "arch" INTEGER DEFAULT NULL,
  "cooke_pts" INTEGER DEFAULT NULL,
  "sweeps" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "region_fine" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "amount" REAL DEFAULT NULL,
  "reason" TEXT DEFAULT NULL,
  "levied_at" TEXT DEFAULT NULL,
  "levied_by" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "region_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "setting" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "region_setting__region_tag" ON "region_setting" ("region", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "region_setting__event" ON "region_setting" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "region_setting__region" ON "region_setting" ("region");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "result" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rank" INTEGER DEFAULT NULL,
  "place" TEXT DEFAULT NULL,
  "percentile" NUMERIC DEFAULT NULL,
  "result_set" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "student" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "panel" INTEGER DEFAULT NULL,
  "cache" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result__entry" ON "result" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result__student" ON "result" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result__result_set" ON "result" ("result_set");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result__round" ON "result" ("round");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result__fk_school" ON "result" ("school");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "result_key" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "description" TEXT DEFAULT NULL,
  "no_sort" INTEGER DEFAULT NULL,
  "sort_desc" INTEGER DEFAULT NULL,
  "result_set" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_key__result_set" ON "result_key" ("result_set");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "result_set" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "entity" TEXT DEFAULT NULL,
  "label" TEXT DEFAULT NULL,
  "bracket" INTEGER NOT NULL DEFAULT 0,
  "published" INTEGER NOT NULL DEFAULT 0,
  "coach" INTEGER DEFAULT NULL,
  "generated" TEXT DEFAULT NULL,
  "cache" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "sweep_set" INTEGER DEFAULT NULL,
  "sweep_award" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "nsda_category" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "code" TEXT DEFAULT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_set__tourn" ON "result_set" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_set__event" ON "result_set" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_set__result_labels" ON "result_set" ("label", "event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_set__fk_rs_nsda_category" ON "result_set" ("nsda_category");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "result_value" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "value" TEXT DEFAULT NULL,
  "priority" INTEGER DEFAULT NULL,
  "result" INTEGER DEFAULT NULL,
  "result_key" INTEGER NOT NULL DEFAULT 0,
  "protocol" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_value__result" ON "result_value" ("result");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "result_value__result_key" ON "result_value" ("result_key");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "room" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "building" TEXT DEFAULT NULL,
  "name" TEXT NOT NULL DEFAULT '',
  "quality" INTEGER DEFAULT NULL,
  "capacity" INTEGER DEFAULT NULL,
  "rowcount" INTEGER DEFAULT NULL,
  "seats" INTEGER DEFAULT NULL,
  "inactive" INTEGER NOT NULL DEFAULT 0,
  "deleted" INTEGER NOT NULL DEFAULT 0,
  "ada" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT DEFAULT NULL,
  "url" TEXT DEFAULT NULL,
  "password" TEXT DEFAULT NULL,
  "judge_url" TEXT DEFAULT NULL,
  "judge_password" TEXT DEFAULT NULL,
  "api" INTEGER DEFAULT NULL,
  "site" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "room__uk_room" ON "room" ("site", "name");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "room__site" ON "room" ("site");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "room__api" ON "room" ("api");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "room_strike" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "room" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "room_strike__room" ON "room_strike" ("room");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "round" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "name" INTEGER DEFAULT NULL,
  "label" TEXT DEFAULT NULL,
  "flighted" INTEGER DEFAULT NULL,
  "published" INTEGER DEFAULT NULL,
  "post_primary" INTEGER DEFAULT NULL,
  "post_secondary" INTEGER DEFAULT NULL,
  "post_feedback" INTEGER DEFAULT NULL,
  "paired_at" TEXT DEFAULT NULL,
  "start_time" TEXT DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "timeslot" INTEGER DEFAULT NULL,
  "site" INTEGER DEFAULT NULL,
  "protocol" INTEGER DEFAULT NULL,
  "runoff" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "round__uk_round" ON "round" ("name", "event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round__timeslot" ON "round" ("timeslot");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round__event" ON "round" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round__tiebreak_set" ON "round" ("protocol");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round__fk_round_site" ON "round" ("site");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "round_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "round" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "round_setting__round_tag" ON "round_setting" ("round", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round_setting__round" ON "round_setting" ("round");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "round_setting__tag" ON "round_setting" ("tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpool" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "tourn" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool__tourn" ON "rpool" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpool_room" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rpool" INTEGER DEFAULT NULL,
  "room" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool_room__room" ON "rpool_room" ("room");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool_room__room_group" ON "rpool_room" ("rpool");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpool_round" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rpool" INTEGER DEFAULT NULL,
  "round" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool_round__round" ON "rpool_round" ("round");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool_round__room_group" ON "rpool_round" ("rpool");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpool_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "rpool" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "rpool_setting__uk_rpool" ON "rpool_setting" ("rpool", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "rpool_setting__rpool" ON "rpool_setting" ("rpool");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "school" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "code" TEXT DEFAULT NULL,
  "onsite" INTEGER NOT NULL DEFAULT 0,
  "tourn" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "district" INTEGER DEFAULT NULL,
  "registered_by" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school__chapter" ON "school" ("chapter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school__tourn" ON "school" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school__region" ON "school" ("region");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school__fk_school_registered_by" ON "school" ("registered_by");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "school_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_changed" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "school_setting__school_tag" ON "school_setting" ("school", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "school_setting__school" ON "school_setting" ("school");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "score" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" REAL NOT NULL DEFAULT 0,
  "content" TEXT DEFAULT NULL,
  "topic" TEXT DEFAULT NULL,
  "speech" INTEGER NOT NULL DEFAULT 0,
  "position" INTEGER NOT NULL DEFAULT 0,
  "ballot" INTEGER DEFAULT NULL,
  "student" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "score__uk_score_restraint" ON "score" ("tag", "ballot", "speech", "position", "student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "score__student" ON "score" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "score__ballot" ON "score" ("ballot");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "score__tags" ON "score" ("ballot", "tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "server" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "hostname" TEXT NOT NULL,
  "status" TEXT DEFAULT NULL,
  "linode_id" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "timestamp" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "server__uk_linode_id" ON "server" ("linode_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "server__linode_id" ON "server" ("linode_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT NOT NULL,
  "subtype" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "value_type" TEXT DEFAULT NULL,
  "conditions" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "setting__tag" ON "setting" ("tag");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "setting_label" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "lang" TEXT DEFAULT NULL,
  "label" TEXT DEFAULT NULL,
  "guide" TEXT DEFAULT NULL,
  "options" TEXT DEFAULT NULL,
  "setting" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "setting_label__fk_setting_label" ON "setting_label" ("setting");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shift" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "type" TEXT DEFAULT NULL,
  "fine" INTEGER DEFAULT NULL,
  "no_hires" INTEGER NOT NULL DEFAULT 0,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "category" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "shift__fk_shift_category" ON "shift" ("category");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "site" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL DEFAULT '',
  "online" INTEGER NOT NULL DEFAULT 0,
  "directions" TEXT DEFAULT NULL,
  "dropoff" TEXT DEFAULT NULL,
  "host" INTEGER DEFAULT NULL,
  "circuit" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "site__circuit" ON "site" ("circuit");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stats" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "tag" TEXT DEFAULT NULL,
  "value" NUMERIC DEFAULT NULL,
  "event" INTEGER NOT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "stats__event" ON "stats" ("event");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "strike" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT DEFAULT NULL,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "registrant" INTEGER NOT NULL DEFAULT 0,
  "conflict" INTEGER NOT NULL DEFAULT 0,
  "conflictee" INTEGER NOT NULL DEFAULT 0,
  "tourn" INTEGER DEFAULT NULL,
  "judge" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "school" INTEGER DEFAULT NULL,
  "region" INTEGER DEFAULT NULL,
  "district" INTEGER DEFAULT NULL,
  "timeslot" INTEGER DEFAULT NULL,
  "shift" INTEGER DEFAULT NULL,
  "entered_by" INTEGER DEFAULT NULL,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "dioregion" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strike__judge" ON "strike" ("judge");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strike__school" ON "strike" ("school");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strike__entry" ON "strike" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strike__tourn" ON "strike" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "strike__event" ON "strike" ("event");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "first" TEXT NOT NULL DEFAULT '',
  "middle" TEXT DEFAULT NULL,
  "last" TEXT NOT NULL DEFAULT '',
  "phonetic" TEXT DEFAULT NULL,
  "grad_year" INTEGER DEFAULT NULL,
  "novice" INTEGER NOT NULL DEFAULT 0,
  "retired" INTEGER NOT NULL DEFAULT 0,
  "gender" TEXT DEFAULT NULL,
  "nsda" INTEGER DEFAULT NULL,
  "chapter" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "person_request" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student__last" ON "student" ("last");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student__first" ON "student" ("first");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student__person" ON "student" ("person");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student__nsda" ON "student" ("nsda");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student__chapter" ON "student" ("chapter");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_ballot" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "panel" INTEGER NOT NULL DEFAULT 0,
  "entry" INTEGER NOT NULL DEFAULT 0,
  "voter" INTEGER NOT NULL DEFAULT 0,
  "value" INTEGER DEFAULT NULL,
  "entered_by" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_ballot__panel" ON "student_ballot" ("panel");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_ballot__entry" ON "student_ballot" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_ballot__voter" ON "student_ballot" ("voter");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student" INTEGER DEFAULT NULL,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "setting" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "student_setting__student_tag" ON "student_setting" ("student", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_setting__student" ON "student_setting" ("student");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_setting__sstag" ON "student_setting" ("tag", "student");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_vote" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" INTEGER DEFAULT NULL,
  "panel" INTEGER DEFAULT NULL,
  "entry" INTEGER DEFAULT NULL,
  "voter" INTEGER DEFAULT NULL,
  "entered_by" INTEGER DEFAULT NULL,
  "entered_at" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "student_vote__sv_evp" ON "student_vote" ("panel", "entry", "voter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_vote__entry" ON "student_vote" ("entry");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_vote__voter" ON "student_vote" ("voter");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "student_vote__panel" ON "student_vote" ("panel");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_award" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT DEFAULT NULL,
  "target" TEXT DEFAULT NULL,
  "period" TEXT DEFAULT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  "min_schools" INTEGER NOT NULL DEFAULT 0,
  "min_entries" INTEGER NOT NULL DEFAULT 0,
  "circuit" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_award_event" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "abbr" TEXT DEFAULT NULL,
  "level" TEXT DEFAULT NULL,
  "sweep_set" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_award_event__sweep_set" ON "sweep_award_event" ("sweep_set");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_event" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "sweep_set" INTEGER DEFAULT NULL,
  "event" INTEGER DEFAULT NULL,
  "event_type" TEXT DEFAULT NULL,
  "event_level" TEXT DEFAULT NULL,
  "nsda_category" INTEGER DEFAULT NULL,
  "sweep_award_event" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_event__sweep_set" ON "sweep_event" ("sweep_set");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_event__event" ON "sweep_event" ("event");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_event__nsda_category" ON "sweep_event" ("nsda_category");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_include" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "parent" INTEGER DEFAULT NULL,
  "child" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_include__fk_sweepinclude_parent" ON "sweep_include" ("parent");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_include__fk_sweepinclude_child" ON "sweep_include" ("child");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_rule" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "value" TEXT DEFAULT NULL,
  "place" INTEGER DEFAULT NULL,
  "count" TEXT DEFAULT NULL,
  "rev_min" INTEGER DEFAULT NULL,
  "count_round" INTEGER DEFAULT NULL,
  "truncate" INTEGER DEFAULT NULL,
  "sweep_set" INTEGER DEFAULT NULL,
  "protocol" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_rule__sweep_set" ON "sweep_rule" ("sweep_set");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sweep_set" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "sweep_award" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_set__tourn" ON "sweep_set" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sweep_set__sweep_award" ON "sweep_set" ("sweep_award");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tabroom_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tabroom_setting__uk_tabroom_setting" ON "tabroom_setting" ("tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tabroom_setting__person" ON "tabroom_setting" ("person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tiebreak" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "count" TEXT NOT NULL DEFAULT '0',
  "count_round" INTEGER DEFAULT NULL,
  "truncate" INTEGER DEFAULT NULL,
  "truncate_smallest" INTEGER NOT NULL DEFAULT 0,
  "multiplier" INTEGER DEFAULT NULL,
  "violation" INTEGER DEFAULT NULL,
  "result" TEXT DEFAULT NULL,
  "priority" INTEGER DEFAULT NULL,
  "chair" TEXT NOT NULL DEFAULT 'all',
  "highlow" INTEGER DEFAULT NULL,
  "highlow_count" INTEGER DEFAULT NULL,
  "highlow_threshold" INTEGER DEFAULT NULL,
  "child" INTEGER DEFAULT NULL,
  "protocol" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "highlow_target" INTEGER DEFAULT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tiebreak__tiebreak_set" ON "tiebreak" ("protocol");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "timeslot" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT DEFAULT NULL,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "timeslot__tourn" ON "timeslot" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "timeslot__start" ON "timeslot" ("start");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "timeslot__end" ON "timeslot" ("end");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "topic" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tag" TEXT DEFAULT NULL,
  "source" TEXT DEFAULT NULL,
  "event_type" TEXT DEFAULT NULL,
  "pattern" TEXT DEFAULT NULL,
  "topic_text" TEXT DEFAULT NULL,
  "school_year" INTEGER DEFAULT NULL,
  "sort_order" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
  "created_by" INTEGER NOT NULL DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL DEFAULT '',
  "city" TEXT DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "country" TEXT DEFAULT NULL,
  "tz" TEXT DEFAULT NULL,
  "webname" TEXT DEFAULT NULL,
  "hidden" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "reg_start" TEXT DEFAULT NULL,
  "reg_end" TEXT DEFAULT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn__start" ON "tourn" ("start");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn__end" ON "tourn" ("end");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn_circuit" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "approved" INTEGER NOT NULL DEFAULT 0,
  "tourn" INTEGER NOT NULL DEFAULT 0,
  "circuit" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tourn_circuit__uk_tourn_circuit" ON "tourn_circuit" ("tourn", "circuit");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_circuit__tourn" ON "tourn_circuit" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_circuit__circuit" ON "tourn_circuit" ("circuit");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn_fee" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "start" TEXT DEFAULT NULL,
  "end" TEXT DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "amount" NUMERIC DEFAULT NULL,
  "reason" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_fee__tourn" ON "tourn_fee" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn_ignore" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tourn" INTEGER DEFAULT NULL,
  "person" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_ignore__tourn" ON "tourn_ignore" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_ignore__person" ON "tourn_ignore" ("person");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn_setting" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tourn" INTEGER NOT NULL DEFAULT 0,
  "tag" TEXT NOT NULL DEFAULT '',
  "value" TEXT NOT NULL DEFAULT '',
  "value_text" TEXT DEFAULT NULL,
  "value_date" TEXT DEFAULT NULL,
  "setting" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tourn_setting__uk_tourn_setting" ON "tourn_setting" ("tourn", "tag");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tourn_setting__tourn_tag" ON "tourn_setting" ("tourn", "tag");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_setting__tourn" ON "tourn_setting" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_setting__tags" ON "tourn_setting" ("tag", "tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tourn_site" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tourn" INTEGER DEFAULT NULL,
  "site" INTEGER NOT NULL DEFAULT 0,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tourn_site__tourn_site_unique" ON "tourn_site" ("tourn", "site");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_site__site" ON "tourn_site" ("site");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tourn_site__tourn" ON "tourn_site" ("tourn");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "webpage" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT DEFAULT NULL,
  "slug" TEXT DEFAULT NULL,
  "content" TEXT DEFAULT NULL,
  "sidebar" TEXT DEFAULT NULL,
  "published" INTEGER NOT NULL DEFAULT 0,
  "sitewide" INTEGER NOT NULL DEFAULT 0,
  "special" TEXT DEFAULT NULL,
  "page_order" INTEGER DEFAULT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "parent" INTEGER DEFAULT NULL,
  "last_editor" INTEGER DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webpage__tourn" ON "webpage" ("tourn");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webpage__sitewide" ON "webpage" ("sitewide");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "weekend" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "start" TEXT NOT NULL,
  "end" TEXT NOT NULL,
  "reg_start" TEXT NOT NULL,
  "reg_end" TEXT NOT NULL,
  "freeze_deadline" TEXT NOT NULL,
  "drop_deadline" TEXT NOT NULL,
  "judge_deadline" TEXT NOT NULL,
  "fine_deadline" TEXT NOT NULL,
  "tourn" INTEGER DEFAULT NULL,
  "site" INTEGER DEFAULT NULL,
  "city" TEXT DEFAULT NULL,
  "state" TEXT DEFAULT NULL,
  "timestamp" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "weekend__tourn" ON "weekend" ("tourn");
