services: 

  # app-dev:
  #   build: ./client/
  #   # command: vite dev --host
  #   container_name: app-dev
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   expose:
  #     - "5173"
  #   networks:
  #     - caddy
  #   working_dir: /app
  #   volumes:
  #     - /app/node_modules
  #   environment:
  #     - PUBLIC_API=http://localhost:8090
  #   labels:
  #     caddy: app.debate.com.co
  #     caddy.reverse_proxy: "{{upstreams 5173}}"

  vector-api:
    build: ./vector-api
    command:  uvicorn main:app --reload --host 0.0.0.0 --port 8000
    container_name: vector-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    expose:
      - "8000"
    working_dir: /app
    volumes:
      - ./vector-api:/app
    networks:
      - caddy
    labels:
      caddy: vector-api.debate.com.co
      caddy.reverse_proxy: "{{upstreams 8000}}"

  # Caddy - proxy server router for containers
  router:  
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: router
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/caddy/data:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy

  # Pocketbase - sqlite, auth, api, admin ui
  db-admin:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "8090:8090"
    expose:
      - "8090"
    networks:
      - caddy
    volumes:
      - pb_data:/pb_data
    labels:
      caddy: api.debate.com.co
      caddy.reverse_proxy: "{{upstreams 8090}}"

volumes:
  pb_data:

networks:
  caddy:
    external: true