// Generated by scripts/configure.mjs from profiles/debate-ai.json. Do not edit by hand.
pub const DEEP_LINK_SCHEME: &str = "debateai";
pub const APP_URL: &str = "https://debate-ai.com";
/// (id, label, url) for each place the app can load from; see app_source.rs.
pub const SOURCES: &[(&str, &str, &str)] = &[
    ("live", "debate-ai.com", "https://debate-ai.com"),
    ("beta", "Beta (d.ebate.app)", "https://d.ebate.app"),
    ("offline", "Offline (built into the app)", "offline/index.html"),
];
pub const DEFAULT_SOURCE: &str = "live";
