// @vitest-environment jsdom
/**
 * @fileoverview The "By speech" tab beside a video with a per-speech AI
 * summary: one tab per speech, views inside each, seeking and following
 * playback.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, createElement } from "react";
import { createRoot, type Root } from "react-dom/client";
import { WatchSidePanel } from "../src/components/watch/WatchSidePanel";
import type { SpeechFocusRequest } from "../src/components/watch/WatchRoundPanel";
import type { VideoDocument } from "../src/lib/video-documents";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const summary: VideoDocument = {
  videoId: "vid1",
  kind: "summary",
  body: "## 1AC\n\nFrames the **space race**.\n\n## CX\n\nPins the plan.\n\n## 1NC\n\nFive off.",
  author: "ai",
  model: "claude-opus-5-5",
};

const transcript: VideoDocument = {
  videoId: "vid1",
  kind: "transcript",
  body: "## 1AC (0:00)\n\nThe new space race.\n\n## CX (6:00)\n\nWhat does the plan mandate?\n\n## 1NC (9:00)\n\nFive off.",
  author: "editor",
};

describe("WatchSidePanel by speech", () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    window.localStorage.clear();
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(() => {
    act(() => root.unmount());
    container.remove();
  });

  function render(
    documents: VideoDocument[],
    { currentTime = 0, onSeek = () => {}, focusSpeech = null as SpeechFocusRequest | null } = {},
  ) {
    act(() => {
      root.render(
        createElement(WatchSidePanel, {
          sentences: [],
          captionsLoading: false,
          documents,
          currentTime,
          onSeek,
          focusSpeech,
        }),
      );
    });
  }

  const speechTabs = () =>
    Array.from(container.querySelectorAll('[aria-label="Speeches"] [role="tab"]')) as HTMLButtonElement[];
  const selectedSpeech = () => speechTabs().find((tab) => tab.getAttribute("aria-selected") === "true")?.textContent;
  const panelText = () => container.querySelector('[role="tabpanel"]')?.textContent ?? "";

  it("opens on a tab per speech ahead of the document tabs", () => {
    render([summary, transcript]);
    const outer = Array.from(container.querySelectorAll('[aria-label="Beside this video"] [role="tab"]'));
    expect(outer.map((tab) => tab.textContent)).toEqual(["By speech3 speeches", "Speeches", "Summary"]);
    // The 1AC starts at 0:00, so it is already the speech playing.
    expect(speechTabs().map((tab) => tab.textContent)).toEqual(["1AC(playing)", "CX", "1NC"]);
    expect(container.querySelector("strong")?.textContent).toBe("space race");
    expect(panelText()).toContain("Generated by claude-opus-5-5");
  });

  it("switches between a speech's summary and its transcript", () => {
    render([summary, transcript]);
    const transcriptView = Array.from(container.querySelectorAll('[role="tab"]')).find(
      (tab) => tab.textContent === "Transcript",
    ) as HTMLButtonElement;
    act(() => transcriptView.click());
    expect(panelText()).toContain("The new space race.");
    expect(panelText()).not.toContain("Generated by");

    // The chosen view sticks when moving to another speech.
    act(() => speechTabs()[1].click());
    expect(panelText()).toContain("What does the plan mandate?");
  });

  it("seeks to a timed speech when its tab is clicked", () => {
    const onSeek = vi.fn();
    render([summary, transcript], { onSeek });
    act(() => speechTabs()[2].click());
    expect(onSeek).toHaveBeenCalledWith(540);
    expect(selectedSpeech()).toBe("1NC");
  });

  it("follows playback to the speech that starts, and marks it playing", () => {
    render([summary, transcript], { currentTime: 10 });
    expect(selectedSpeech()).toBe("1AC(playing)");
    render([summary, transcript], { currentTime: 6 * 60 + 5 });
    expect(selectedSpeech()).toBe("CX(playing)");
  });

  it("opens a speech the timeline asks for", () => {
    render([summary, transcript]);
    const summaryTab = Array.from(container.querySelectorAll('[role="tab"]')).find(
      (tab) => tab.textContent === "Summary",
    ) as HTMLButtonElement;
    act(() => summaryTab.click());
    expect(speechTabs()).toHaveLength(0);

    render([summary, transcript], { focusSpeech: { key: "1NC#1", seq: 1 } });
    expect(selectedSpeech()).toBe("1NC");
  });

  it("simulates alternative responses to a speech and charts the ballots", async () => {
    const reply = {
      actual: { assessment: "Reads five off.", ballot: { winner: "neg", affWinProbability: 40, rfd: "Spec." } },
      alternatives: [
        { title: "Two-off strategy", approach: "collapse", outline: ["Spec", "DA"], tradeoff: "Less spread.", ballot: { winner: "neg", affWinProbability: 20, rfd: "Deeper DA." } },
        { title: "Kritik only", approach: "kritik", outline: ["Cap K"], tradeoff: "Risky.", ballot: { winner: "aff", affWinProbability: 55, rfd: "Perm." } },
      ],
      keyClash: ["Spec"],
    };
    const fetchMock = vi.fn(async () => new Response(JSON.stringify({ text: JSON.stringify(reply) }), { status: 200 }));
    vi.stubGlobal("fetch", fetchMock);
    try {
      render([summary, transcript]);
      act(() => speechTabs()[2].click());
      const outcomesView = Array.from(container.querySelectorAll('[role="tab"]')).find(
        (tab) => tab.textContent === "Outcomes",
      ) as HTMLButtonElement;
      act(() => outcomesView.click());
      expect(panelText()).toContain("What else could the 1NC have done?");

      const simulate = Array.from(container.querySelectorAll("button")).find((button) => button.textContent === "Simulate")!;
      await act(async () => {
        simulate.click();
      });
      const body = JSON.parse((fetchMock.mock.calls[0] as unknown as [string, RequestInit])[1].body as string);
      expect(body.messages[0].content).toContain("## The speech to re-imagine: 1NC");

      // Swings are for the neg, who gave the 1NC: 40 → 20 aff is +20 for the neg.
      expect(panelText()).toContain("Two-off strategy");
      expect(panelText()).toContain("Strongest");
      expect(panelText()).toContain("Ballot flips");
      expect(panelText()).toContain("Deeper DA.");
      expect(speechTabs()[2].querySelector('[aria-label="has simulated outcomes"]')).not.toBeNull();

      // Leaving and coming back shows the saved run instead of asking again.
      act(() => speechTabs()[0].click());
      act(() => speechTabs()[2].click());
      expect(panelText()).toContain("Two-off strategy");
      expect(fetchMock).toHaveBeenCalledTimes(1);
    } finally {
      vi.unstubAllGlobals();
    }
  });

  it("surfaces the proxy's error, e.g. when signed out", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ error: "Sign in to use AI features." }), { status: 401 })));
    try {
      render([summary, transcript]);
      const outcomesView = Array.from(container.querySelectorAll('[role="tab"]')).find(
        (tab) => tab.textContent === "Outcomes",
      ) as HTMLButtonElement;
      act(() => outcomesView.click());
      const simulate = Array.from(container.querySelectorAll("button")).find((button) => button.textContent === "Simulate")!;
      await act(async () => {
        simulate.click();
      });
      expect(container.querySelector('[role="alert"]')?.textContent).toContain("Sign in to use AI features.");
    } finally {
      vi.unstubAllGlobals();
    }
  });

  it("leaves a video without a per-speech summary as it was", () => {
    render([transcript, { ...summary, body: "One paragraph." }]);
    expect(speechTabs()).toHaveLength(0);
  });
});
