/**
 * The SQL-rewriting half of `scripts/migrate-d1.ts` — split out so it can be
 * unit-tested without a database or a `wrangler` binary.
 *
 * Migrations under `drizzle/` are generated by drizzle-kit for a database that
 * starts empty and receives every file in order. Production is not that: it
 * has been live since 2024, its migration lineage was regenerated at some
 * point, and it can already hold some of what a file is about to create. The
 * two transforms here are what let a file be re-applied to such a database and
 * still converge, so the runner can treat *any* remaining error as real
 * instead of blanket-ignoring failures the way the shell loop it replaces did.
 */

/**
 * Splits a migration into statements, on drizzle's marker when present and on
 * `;` for the hand-written files that lack it.
 *
 * The line-comment strip deliberately spares `-->`: drizzle's separator is
 * `--> statement-breakpoint`, which is itself a SQL line comment, so a naive
 * `^--.*$` strip removes the very marker the split is about to look for and
 * hands back the entire file as one statement.
 */
export function splitStatements(sql: string): string[] {
  const stripped = sql.replace(/^\s*--(?!>)[^\n]*$/gm, "");
  const parts = stripped.includes("--> statement-breakpoint")
    ? stripped.split("--> statement-breakpoint")
    : stripped.split(/;\s*(?:\n|$)/);
  return parts.map((part) => part.trim().replace(/;$/, "")).filter(Boolean);
}

/**
 * Rewrites `CREATE TABLE`/`CREATE INDEX` to its `IF NOT EXISTS` form.
 *
 * Without this, a file whose first statement collides with an existing table
 * aborts there and its *later* statements — often the new ones that are the
 * whole point of the migration — never run at all.
 */
export function makeIdempotent(statement: string): string {
  return statement.replace(
    /^\s*CREATE\s+(TABLE|(?:UNIQUE\s+)?INDEX)\s+(?!IF\s+NOT\s+EXISTS)/i,
    (_match, kind: string) => `CREATE ${kind} IF NOT EXISTS `,
  );
}

/**
 * SQLite has no `ALTER TABLE … ADD COLUMN IF NOT EXISTS`, so a column add
 * cannot be made idempotent in SQL. The runner instead sends these one at a
 * time and forgives exactly one error text (`BENIGN_ALTER_ERROR`), which is
 * only sound if each is isolated from the statements around it.
 */
export function isAlterAdd(statement: string): boolean {
  return /^\s*ALTER\s+TABLE\b[\s\S]*\bADD\b/i.test(statement);
}

/** The one error a re-applied migration may raise: the column is already there. */
export const BENIGN_ALTER_ERROR = /duplicate column name/i;

export interface MigrationStep {
  /** One statement, or a run of consecutive batchable ones joined by `;`. */
  sql: string;
  /** Whether `BENIGN_ALTER_ERROR` may be forgiven for this step. */
  tolerateDuplicateColumn: boolean;
}

/**
 * Prepares one migration for execution, as an ordered list of steps.
 *
 * Order is the whole point: `0025_flat_wrecker.sql` adds `documents.parent_id`
 * and *then* indexes it, so hoisting every create ahead of every column add —
 * the obvious way to batch — fails with "no such column: parent_id". Runs of
 * consecutive batchable statements are therefore merged, but a column add
 * always splits the run and keeps its position.
 */
export function planMigration(sql: string): MigrationStep[] {
  const steps: MigrationStep[] = [];

  for (const statement of splitStatements(sql)) {
    if (isAlterAdd(statement)) {
      steps.push({ sql: statement, tolerateDuplicateColumn: true });
      continue;
    }
    const previous = steps.at(-1);
    const guarded = makeIdempotent(statement);
    if (previous && !previous.tolerateDuplicateColumn) previous.sql += `;\n${guarded}`;
    else steps.push({ sql: guarded, tolerateDuplicateColumn: false });
  }

  return steps;
}
