#!/bin/bash
# Setup Cloudflare Workers secrets for debate-ai
# Run this after creating your environment variables

echo "Setting up Cloudflare Workers secrets..."
echo ""
echo "You'll need to provide values for the following secrets:"
echo "  - BETTER_AUTH_SECRET (generate with: openssl rand -base64 32)"
echo "  - GOOGLE_CLIENT_ID (from Google Cloud Console)"
echo "  - GOOGLE_CLIENT_SECRET (from Google Cloud Console)"
echo "  - AUTH_DISCORD_ID (optional - from Discord Developer Portal)"
echo "  - AUTH_DISCORD_SECRET (optional)"
echo "  - AUTH_LINKEDIN_ID (optional - from LinkedIn Developers)"
echo "  - AUTH_LINKEDIN_SECRET (optional)"
echo "  - RESEND_API_KEY (optional - from resend.com for email)"
echo "  - NEXT_PUBLIC_BASE_URL (your production URL, e.g., https://debate-ai.com)"
echo "  - BETTER_AUTH_ALLOWED_HOSTS (optional - extra hosts this app is served from,"
echo "      comma-separated; see docs/auth-domains.md)"
echo "  - YOUTUBE_API_KEY (required for /admin YouTube resync)"
echo "  - ADMIN_EMAILS (optional - comma-separated allowlist for /admin; open to everyone if unset)"
echo "  - CARD_IMPORT_TOKEN (optional - bearer token for the debate-cards-upload CLI; without it, card imports need an admin session)"
echo "  - YOUTUBE_PROXY_URL (optional - fetch-through proxy template for transcripts, e.g. https://proxy.example.com/fetch?key=K&url={url}; see docs/youtube-transcript-proxy.md)"
echo "  - TURNSTILE_SECRET_KEY (optional - Cloudflare Turnstile secret; pair with a TURNSTILE_SITE_KEY variable to gate first page loads, see internals/turnstile-bot-gate)"
echo ""
echo "To set a secret, run:"
echo "  npx wrangler secret put SECRET_NAME"
echo ""
echo "Example:"
echo "  npx wrangler secret put BETTER_AUTH_SECRET"
echo ""
