-- The YouTube channels the weekly resync scans. `youtube_channels` is declared
-- in apps/debate-ai.com/lib/database/schema.ts (youtubeChannels) and managed
-- from /admin's channels tab; this file creates it on a database that lacks it
-- and seeds it with every channel in src/youtube/channel-config.ts, so the
-- tracked list lives in SQL rather than only in source. The insert ignores a
-- name the unique index already holds, so a channel an admin already added or
-- paused is left exactly as it is. Applied by .github/scripts/migrate-d1.ts,
-- which runs package migrations after the app's own.
-- apps/debate-ai.com/lib/youtube/__tests__/youtube-channels-seed.test.ts keeps
-- this file, schema.ts and channel-config.ts in step.
CREATE TABLE IF NOT EXISTS `youtube_channels` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`channel_id` text,
	`name` text NOT NULL,
	`enabled` integer DEFAULT true NOT NULL,
	`added_by` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `idx_youtube_channels_name` ON `youtube_channels` (`name`);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `idx_youtube_channels_channel_id` ON `youtube_channels` (`channel_id`);
--> statement-breakpoint
INSERT OR IGNORE INTO `youtube_channels` (`name`) VALUES
	('jettsmith7'),
	('artemisway-g2x'),
	('ajapdebate'),
	('KansasDebate-wd4vf'),
	('spencerandersonmcelligott'),
	('Adi_Arora_PF'),
	('barkleyforumvideos3220'),
	('DebateArchive2'),
	('Debatedrills'),
	('championbriefs1508'),
	('su.debate'),
	('ResolvedDebate'),
	('PolicyDebateCentral'),
	('pfvideos9234'),
	('ddidebate4071'),
	('DebateStreamDB8'),
	('LynbrookDebate'),
	('thatdebatekid5313'),
	('NSD_DebateCamp'),
	('lasadebate'),
	('CEDADebate'),
	('KentuckyDebate'),
	('sailorferrets'),
	('wakedebate8636'),
	('exodusfiles3478'),
	('SolvencyAdvocate'),
	('northbrowardmr4523'),
	('TexasDebate'),
	('jacob_wilkus'),
	('arvindshankar2481'),
	('NDT-jl6oi'),
	('atrujillo9'),
	('UNTDebate'),
	('vintagedebatevids'),
	('georgetowndebateseminar1234'),
	('BillBatterman'),
	('msudebate6544'),
	('ProfessorGraham'),
	('michigandebate7440'),
	('ArrmanKapoor'),
	('BreakDebate'),
	('DebateMatters'),
	('ElmerYangDebateVideos'),
	('IndianaSpeechandDebate'),
	('IvyLivestream1'),
	('IvyLivestream2'),
	('IvyLivestream3'),
	('IvyLivestream4'),
	('IvyLivestream6'),
	('NIHDVideoChannel'),
	('OHSPEECHDEBATE'),
	('PeterTulloch'),
	('VictoryBriefs'),
	('VikrantDebate'),
	('aaronlangerman4525'),
	('aayush-appan-1'),
	('ansonfung182'),
	('arjunnayagadurai1808'),
	('beyondresolved9910'),
	('classicdebatecamp9738'),
	('danielgarepisholland'),
	('davidherrera8285'),
	('flexdebate8737'),
	('fluxnfiction5559'),
	('goldenstate6086'),
	('greenhilldebate9898'),
	('hannahowenspierre'),
	('hopezerafa1111'),
	('ibrahimarain6382'),
	('idpdebates'),
	('ishaanbanerjee13'),
	('itachi_cloud9255'),
	('jmdebatevideos'),
	('ldben4258'),
	('legacydebatevideos6944'),
	('lynbrookld'),
	('nsdaspeechanddebate'),
	('outreachdebate'),
	('peanutbuttercrackers9106'),
	('ryanpanjwani2557'),
	('sreyaashdas4869'),
	('strakejesuitdebate2958'),
	('vishvakbandi9909'),
	('ziondixon7141');
