/**
 * @file source.tsx
 * @description Fumadocs source loader configuration and page structure.
 */
// Generated by fumadocs-mdx from ../../source.config.ts (the web app's Vite
// plugin at build and dev time, `bun run typecheck` here otherwise).
import { docs } from '../../.source/server'
import {
  type InferMetaType,
  type InferPageType,
  type LoaderPlugin,
  loader,
} from 'fumadocs-core/source'
import { lucideIconsPlugin } from 'fumadocs-core/source/lucide-icons'
import { openapiPlugin } from 'fumadocs-openapi/server'
import { DOCS_BASE_PATH, withBasePath } from './base-path'

export const source = loader({
  // The web app mounts these pages at `app/docs`, and there is no `basePath`
  // to add the prefix, so every page URL carries it (see ./base-path.ts).
  baseUrl: DOCS_BASE_PATH,
  plugins: [pageTreeCodeTitles(), lucideIconsPlugin(), openapiPlugin()],
  source: docs.toFumadocsSource(),
})

function pageTreeCodeTitles(): LoaderPlugin {
  return {
    transformPageTree: {
      file(node) {
        if (
          typeof node.name === 'string' &&
          (node.name.endsWith('()') || node.name.match(/^<\w+ \/>$/))
        ) {
          return {
            ...node,
            name: <code className='text-[0.8125rem]'>{node.name}</code>,
          }
        }
        return node
      },
    },
  }
}


/**
 * Origin-absolute URL of a page's processed Markdown, served by
 * `routes/llms-mdx-route.ts` (mounted at `/docs/llms.mdx/…`).
 *
 * The callers (`LLMCopyButton`, `AskAIDropdown`) `fetch` it and resolve it
 * against `window.location.origin`. The docs root has no slug of its own, so
 * it is addressed as `index.mdx`.
 *
 * @param page - The page to link to.
 */
export function pageMarkdownUrl(page: InferPageType<typeof source>): string {
  const slugs = page.slugs.length > 0 ? page.slugs : ['index'];
  return withBasePath(`/llms.mdx/${slugs.join('/')}.mdx`);
}

export async function getLLMText(page: InferPageType<typeof source>) {
  const processed = await page.data.getText('processed');

  return `# ${page.data.title} (${page.url})

${processed}`;
}

export type Page = InferPageType<typeof source>
export type Meta = InferMetaType<typeof source>
