const fs = require('fs');
const path = require('path');
const pkg = require('../package.json');

const VERSION = pkg.version;
const folderPath = './.next/static';

function getAllFilesInDir(dir) {
  if (!fs.existsSync(dir)) {
    console.warn(`Directory ${dir} does not exist. Creating empty file list.`);
    return [];
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? getAllFilesInDir(fullPath) : [fullPath];
  });
}

// App routes to cache for offline navigation
const appRoutes = ['/', '/debate', '/videos', '/lectures', '/rank', '/cards', '/edit'];

// Public static assets
const publicAssets = [
  '/favicon.ico',
  '/favicon-192.png',
  '/favicon-512.png',
  '/apple-touch-icon.png',
  '/site.webmanifest',
];

// Next.js static files served at /_next/static/...
const staticFiles = getAllFilesInDir(folderPath)
  .filter(f => !f.endsWith('.map') && !f.includes('node_modules'))
  .map(f => f.replace(/^\.next/, '/_next'));

const allFiles = [...appRoutes, ...publicAssets, ...staticFiles];

const sw = `// Service Worker v${VERSION} — generated by scripts/generate.js
const VERSION = '${VERSION}';
const APP_FILE_LIST = ${JSON.stringify(allFiles, null, 2)};

const sw = self;

async function onInstall() {
  console.info('SW : Install : ' + VERSION);
  const cache = await caches.open(VERSION);
  const results = await Promise.allSettled(
    APP_FILE_LIST.map(async (url) => {
      try {
        const response = await fetch(url);
        if (response.ok) {
          await cache.put(url, response);
        } else {
          console.warn('SW : Cache skip (not ok):', url, response.status);
        }
      } catch (err) {
        console.warn('SW : Cache skip (fetch failed):', url, err);
      }
    })
  );
  const cached = results.filter((r) => r.status === 'fulfilled').length;
  console.info('SW : Cached ' + cached + '/' + APP_FILE_LIST.length + ' assets');
}

async function onActivate() {
  console.info('SW : Activate : ' + VERSION);
  const cacheNames = await caches.keys();
  await Promise.all(
    cacheNames.filter((name) => name !== VERSION).map((name) => caches.delete(name))
  );
  return sw.clients.claim();
}

function isNavigationRequest(request) {
  return request.mode === 'navigate' || (request.headers.get('accept') || '').includes('text/html');
}

async function onFetch(event) {
  const url = new URL(event.request.url);

  // Only handle same-origin requests
  if (url.origin !== sw.location.origin) {
    return fetch(event.request);
  }

  const cache = await caches.open(VERSION);

  // Navigation requests: network-first with offline fallback
  if (isNavigationRequest(event.request)) {
    try {
      const response = await fetch(event.request);
      if (response.ok) {
        cache.put(url.pathname, response.clone());
      }
      return response;
    } catch {
      const cached = await cache.match(url.pathname);
      if (cached) return cached;
      const fallback = await cache.match('/');
      if (fallback) return fallback;
      return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
    }
  }

  // Static assets: cache-first with network fallback
  const cached = await cache.match(url.pathname);
  if (cached) return cached;

  try {
    const response = await fetch(event.request);
    if (response.ok && (url.pathname.startsWith('/_next/') || url.pathname.match(/\\.(js|css|png|ico|woff2?)$/))) {
      cache.put(url.pathname, response.clone());
    }
    return response;
  } catch {
    return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
  }
}

sw.addEventListener('install', (event) => {
  sw.skipWaiting();
  event.waitUntil(onInstall());
});
sw.addEventListener('activate', (event) => event.waitUntil(onActivate()));
sw.addEventListener('fetch', (event) => event.respondWith(onFetch(event)));
`;

fs.writeFileSync('./public/service-worker.js', sw);
console.log(`Generated public/service-worker.js v${VERSION} with ${allFiles.length} files`);
