/// <reference lib="webworker" />
import { VERSION } from "./version";
import { APP_FILE_LIST } from "./app-file-list";

const sw: ServiceWorkerGlobalScope = self as unknown as ServiceWorkerGlobalScope;

// One cache per build. `VERSION` is derived from the contents of `dist/client`
// (see generate.cjs), so a deploy that changes any client asset lands in a new
// cache and `onActivate` drops the previous one. Keying the cache on the
// package version instead meant every deploy reused the same cache: entries
// from an older build survived forever and were served in preference to the
// files the new build actually shipped.
const CACHE_NAME = `debate-ai-${VERSION}`;

// Everything the build emitted, for cache-first serving. These are the only
// same-origin paths we trust to be immutable within a build.
const PRECACHED = new Set<string>(APP_FILE_LIST);

async function onInstall() {
  console.info("SW : Install : " + VERSION);
  const cache = await caches.open(CACHE_NAME);

  // Cache assets individually so one missing file doesn't break the whole installation.
  // The app is server-rendered (no static index.html), so the navigation shell is
  // the root document `/`; the rest comes from the generated build manifest.
  const assetsToCache = ['/', ...APP_FILE_LIST];
  let cachedCount = 0;

  await Promise.all(
    assetsToCache.map(async (url) => {
      try {
        await cache.add(url);
        cachedCount++;
      } catch (err) {
        console.warn(`SW : Failed to cache asset: ${url}`, err);
      }
    })
  );

  console.info(`SW : Cached ${cachedCount}/${assetsToCache.length} critical assets`);
}

async function onActivate() {
  console.info("SW : Activate : " + VERSION);
  const cacheNames = await caches.keys();
  await Promise.all(
    cacheNames.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))
  );
  // Take control of all clients immediately
  return sw.clients.claim();
}

/**
 * Documents — the HTML shell and the React Server Component payloads the
 * router fetches for client-side navigations.
 *
 * The RSC payload for a route names the exact hashed client chunks of the
 * build that produced it, so it has to be treated like the HTML document and
 * never served from an older build's cache: doing so hands the running app
 * chunk URLs that the current deploy no longer serves, the router's dynamic
 * import rejects, and the destination route renders as a blank page.
 * vinext requests them as `<pathname>.rsc`; Next's own convention is a
 * `?_rsc=` query on the route. Both send `Accept: text/x-component`.
 */
function isDocumentRequest(request: Request, url: URL): boolean {
  if (request.mode === "navigate") return true;
  if (request.method !== "GET") return false;
  const accept = request.headers.get("accept") ?? "";
  if (accept.includes("text/html")) return true;
  if (accept.includes("text/x-component")) return true;
  if (url.pathname.endsWith(".rsc")) return true;
  if (url.searchParams.has("_rsc")) return true;
  return false;
}

/**
 * Speculative fetches the browser makes on its own behalf: `<link
 * rel="prefetch">` (which vinext's router injects for in-viewport links when
 * the RSC navigator is unavailable) and Speculation Rules prerenders.
 *
 * These must never be answered from this worker. The pass-through branch
 * below turns a failed `fetch` into a synthetic `502 Network Error`
 * response, and for a prefetch the browser *stores* that response and hands
 * it to the real navigation that follows — so one dropped prefetch of
 * `/videos` (an aborted request, an extension blocking it, a flaky moment)
 * became a hard 502 on the page the user then clicked through to, which is
 * exactly the "Pass-through fetch failed … 502 (Network Error)" pair seen in
 * the console. Declining to call `respondWith` leaves prefetches to the
 * browser, where a failure is silently discarded the way it is with no
 * service worker at all.
 */
function isSpeculativeRequest(request: Request): boolean {
  // `Sec-Purpose: prefetch` (current) / `Purpose: prefetch` (legacy) are set
  // by the browser and are not forgeable by page script.
  if (request.headers.get("sec-purpose")?.includes("prefetch")) return true;
  if (request.headers.get("purpose") === "prefetch") return true;
  // `<link rel="prefetch" as="document">` in browsers that send neither
  // header: a document request that is not a navigation.
  return request.destination === "document" && request.mode !== "navigate";
}

function isNavigationRequest(request: Request): boolean {
  return request.mode === "navigate" ||
         (request.method === 'GET' && request.headers.get("accept")?.includes("text/html") === true);
}

/**
 * Build output is content-hashed under `/assets/`, and the remaining precached
 * paths (icons, manifest, favicons) are regenerated by every build. Only those
 * are safe to answer from cache before hitting the network; anything else
 * same-origin is generated per request and must go to the network first.
 */
function isImmutableAsset(url: URL): boolean {
  if (url.origin !== sw.location.origin) return false;
  return url.pathname.startsWith("/assets/") || PRECACHED.has(url.pathname);
}

// Cache.put rejects for non-GET requests and can throw on opaque/odd
// responses; it's fire-and-forget by design (the response is already on its
// way back to the page), so failures here must never surface as unhandled
// rejections or fail the request they were piggybacking on.
async function putInCache(request: Request, response: Response): Promise<void> {
  try {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response);
  } catch (err) {
    console.warn(`SW : Failed to cache response for: ${request.url}`, err);
  }
}

async function onFetch(event: FetchEvent): Promise<Response> {
  const url = new URL(event.request.url);

  // Network-first for documents, RSC payloads and API routes (fresh data when
  // online, cached copy only as an offline fallback).
  if (isDocumentRequest(event.request, url) || url.pathname.startsWith('/api/')) {
    try {
      const networkResponse = await fetch(event.request);
      if (networkResponse.ok) {
        await putInCache(event.request, networkResponse.clone());
      }
      return networkResponse;
    } catch (error) {
      const cachedResponse = await caches.match(event.request);
      if (cachedResponse) return cachedResponse;
      // Last resort: serve app shell for navigation requests
      if (isNavigationRequest(event.request)) {
        const cache = await caches.open(CACHE_NAME);
        const offlineShell = await cache.match('/');
        if (offlineShell) return offlineShell;
      }
      throw error;
    }
  }

  // Cache-first for this build's static assets (JS, CSS, images, fonts).
  if (isImmutableAsset(url)) {
    const cachedResponse = await caches.match(event.request);
    if (cachedResponse) return cachedResponse;

    try {
      const networkResponse = await fetch(event.request);
      if (networkResponse.ok) {
        await putInCache(event.request, networkResponse.clone());
      }
      return networkResponse;
    } catch (err) {
      console.warn('SW : Network fetch failed for immutable asset:', event.request.url, err);
      const fallback = await caches.match(event.request);
      if (fallback) return fallback;
      return new Response('Network error', { status: 502, statusText: 'Network Error' });
    }
  }

  // Everything else same-origin (anything the build did not emit) is passed
  // straight through. Wrap the passthrough fetch so network failures do not
  // reject the fetch event promise causing noisy console errors.
  try {
    return await fetch(event.request);
  } catch (err) {
    console.warn('SW : Pass-through fetch failed:', event.request.url, err);
    const cached = await caches.match(event.request);
    if (cached) return cached;
    return new Response('Network error', { status: 502, statusText: 'Network Error' });
  }
}

sw.addEventListener("install", (event) => {
  sw.skipWaiting();
  event.waitUntil(onInstall());
});
sw.addEventListener("activate", (event) => event.waitUntil(onActivate()));
sw.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);

  // Only take responsibility for same-origin GET requests — the only kind
  // this worker knows how to serve (documents, API routes, this build's
  // static assets). Leaving respondWith uncalled for everything else (POSTs,
  // and cross-origin requests like the Cloudflare Insights beacon) hands
  // them back to the browser's normal networking, so a third-party fetch
  // failure there is just that page's problem, not a service-worker
  // "FetchEvent resulted in a network error response" failure.
  if (event.request.method !== "GET" || url.origin !== sw.location.origin) {
    return;
  }

  // Prefetches and prerenders stay with the browser — see
  // `isSpeculativeRequest`. Answering them risks caching a synthetic error
  // response that the following real navigation then reuses.
  if (isSpeculativeRequest(event.request)) {
    return;
  }

  event.respondWith(onFetch(event));
});
