/** @fileoverview Built-in parsing profiles used to tune card-boundary heuristics. */
import type { FormatProfile } from "./types"

/** Built-in parser presets for different source formatting quality levels. */
export const FORMAT_PROFILES: Record<string, FormatProfile> = {
  // Baseline profile for reasonably clean exports with h4 card tags.
  standard: {
    headingTags: ["h1", "h2", "h3", "h4"],
    cardStartHeadings: ["h4"],
    minBlankLinesForBoundary: 1,
    trustParagraphTags: true,
    summaryPatterns: [
      /^Aff\s*[-–]/i,
      /^Neg\s*[-–]/i,
      /^Impact:/i,
      /^Analysis:/i,
      /^Link:/i,
      /^Alt:/i,
      /^Framework:/i,
      /^Uniqueness:/i,
      /^Solvency:/i,
      /^Card:/i,
      /^\d+\.\s*/,
      /^[A-Z][a-z]+\s+\d{2,4}/,
    ],
  },
  // Broader pattern set for mixed formatting and varied debate tag conventions.
  flexible: {
    headingTags: ["h1", "h2", "h3", "h4", "h5", "h6"],
    cardStartHeadings: ["h3", "h4", "h5"],
    minBlankLinesForBoundary: 1,
    trustParagraphTags: true,
    summaryPatterns: [
      /^Aff\s*[-–]/i,
      /^Neg\s*[-–]/i,
      /^Pro\s*[-–]/i,
      /^Con\s*[-–]/i,
      /^Impact[s]?:/i,
      /^Analysis:/i,
      /^Link[s]?:/i,
      /^Alt[ernative]*[s]?:/i,
      /^Framework:/i,
      /^Uniqueness:/i,
      /^Solvency:/i,
      /^Card[s]?:/i,
      /^Claim[s]?:/i,
      /^Warrant[s]?:/i,
      /^Evidence:/i,
      /^Contention[s]?:/i,
      /^Argument[s]?:/i,
      /^\d+[.):]\s+/,
      /^[A-Z]\.\s+/,
      /^[IVX]+\.\s+/,
      /^[A-Z][a-z]+\s+\d{2,4}[,:\s]/,
      /^[A-Z][a-z]+\s+'\d{2}[,:\s]/,
      /^[A-Z][a-z]+\s+and\s+[A-Z][a-z]+\s+\d{2,4}/,
      /^[A-Z][A-Z\s]+\d{2,4}/,
      /^[A-Z][a-z]+\s+et\s+al\.?\s+\d{2,4}/,
      /^['""][^'"]{10,}['""]/, 
      /^['""][A-Z]/,
      /^\*\*[^*]+\*\*/,
      /^__[^_]+__/,
      /^#\s*[A-Z]/,
      /^\[[^\]]+\]/,
      /^<[A-Z][^>]+>/,
    ],
  },
  // Most permissive profile for messy pasted documents where paragraphs may start cards.
  ultraFlexible: {
    headingTags: ["h1", "h2", "h3", "h4", "h5", "h6", "p"],
    cardStartHeadings: ["h3", "h4", "h5", "h6", "p"],
    minBlankLinesForBoundary: 0,
    trustParagraphTags: false,
    summaryPatterns: [
      /^Aff\s*[-–:]/i,
      /^Neg\s*[-–:]/i,
      /^Pro\s*[-–:]/i,
      /^Con\s*[-–:]/i,
      /^Impact[s]?:/i,
      /^Analysis:/i,
      /^Link[s]?:/i,
      /^Alt[ernative]*[s]?:/i,
      /^Framework:/i,
      /^Uniqueness:/i,
      /^Solvency:/i,
      /^Card[s]?:/i,
      /^Claim[s]?:/i,
      /^Warrant[s]?:/i,
      /^Evidence:/i,
      /^Contention[s]?:/i,
      /^Argument[s]?:/i,
      /^\d+[.):]\s+/,
      /^[A-Z]\.\s+/,
      /^[IVX]+\.\s+/,
      /^[A-Z][a-z]+\s+\d{2,4}[,:\s]/,
      /^[A-Z][a-z]+\s+'\d{2}[,:\s]/,
      /^[A-Z][a-z]+\s+and\s+[A-Z][a-z]+\s+\d{2,4}/,
      /^[A-Z][A-Z\s]+\d{2,4}/,
      /^[A-Z][a-z]+\s+et\s+al\.?\s+\d{2,4}/,
      /^['""][^'"]{10,}['""]/, 
      /^['""][A-Z]/,
      /^\*\*[^*]+\*\*/,
      /^__[^_]+__/,
      /^#\s*[A-Z]/,
      /^\[[^\]]+\]/,
      /^<[A-Z][^>]+>/,
    ],
  },
  // Legacy Word export profile where blank lines are more meaningful than tags.
  legacyWord: {
    headingTags: ["h1", "h2", "h3", "h4", "p"],
    cardStartHeadings: ["h4", "p"],
    minBlankLinesForBoundary: 2,
    trustParagraphTags: false,
    summaryPatterns: [/^Aff\s*[-–]/i, /^Neg\s*[-–]/i, /^Impact:/i, /^Analysis:/i, /^Card:/i],
  },
  // Clean HTML profile minimizes pattern assumptions and trusts headings.
  cleanHtml: {
    headingTags: ["h1", "h2", "h3", "h4"],
    cardStartHeadings: ["h4"],
    minBlankLinesForBoundary: 1,
    trustParagraphTags: true,
    summaryPatterns: [],
  },
  // Copy-pasted PDF text often flattens structure, so paragraph tags can start cards.
  pastedPDF: {
    headingTags: ["h1", "h2", "h3", "h4", "p"],
    cardStartHeadings: ["h4", "h3", "p"],
    minBlankLinesForBoundary: 1,
    trustParagraphTags: false,
    summaryPatterns: [/^Aff\s*[-–]/i, /^Neg\s*[-–]/i, /^Impact:/i, /^\d+\./],
  },
}
